on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Mark repo as safe
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config --global --add safe.directory "/__w/zmk-config-roBa/zmk-config-roBa"

      - name: Pristine workspace
        run: |
          git clean -fdx
          rm -rf build/ /tmp/tmp.*

      - name: West sync
        run: |
          west init -l zmk/app
          west update
          west zephyr-export

      - name: Build (settings_reset)
        run: |
          west build -s zmk/app -b seeeduino_xiao_ble -- -DSHIELD=settings_reset
